build_from:
  aarch64: "elitedesire/carbonozrenewables:aarch64-latest"
  amd64: "elitedesire/carbonozrenewables:amd64-latest"
  armhf: "elitedesire/carbonozrenewables:armhf-latest"
  armv7: "elitedesire/carbonozrenewables:armv7-latest"
  i386: "elitedesire/carbonozrenewables:i386-latest"
