build_from:
  aarch64: "homeassistant/aarch64-base:3.18"
  amd64: "homeassistant/amd64-base:3.18"
  armhf: "homeassistant/armhf-base:3.18"
  armv7: "homeassistant/armv7-base:3.18"
  i386: "homeassistant/i386-base:3.18"

labels:
  org.opencontainers.image.title: "CARBONOZ SolarAutopilot V1"
  org.opencontainers.image.description: "CARBONOZ SolarAutopilot V1 for Home Assistant with live Solar dashboard and MQTT inverter control"
  org.opencontainers.image.source: "https://github.com/CARBONOZ-RENEWABLES/carbonoz_solarautopilotV1"
  org.opencontainers.image.licenses: "MIT"

args:
  TEMPIO_VERSION: "2021.09.0"

codenotary:
  signer: "notary@home-assistant.io"
  base_image: "notary@home-assistant.io"
