build_from:
  aarch64: "ghcr.io/carbonoz-renewables/carbonoz_solarautopilotv1:1.0.0-aarch64"
  amd64: "ghcr.io/carbonoz-renewables/carbonoz_solarautopilotv1:1.0.0-amd64"
  armhf: "ghcr.io/carbonoz-renewables/carbonoz_solarautopilotv1:1.0.0-armhf"
  armv7: "ghcr.io/carbonoz-renewables/carbonoz_solarautopilotv1:1.0.0-armv7"
  i386: "ghcr.io/carbonoz-renewables/carbonoz_solarautopilotv1:1.0.0-i386"
