{
 "title": "Charts",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Gruppierung", "label": "grouping in long-term graphs", "query": "1d,1w,30d,1y" },
   {
    "name": "rp",
    "label": "Retention Policy",
    "query": "select rp from forever.rp_config where time >= now() - ${__from}ms order by time asc limit 1"
   },
   { "name": "strompreis", "query": "0.2941" },
   { "name": "verguetung", "query": "0.0854" },
   { "name": "kapazitaet", "label": "Batteriekapazität", "query": "7680" }
  ]
 },
 "panels": [
  {
   "title": "current values and power values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PV Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_voltage_2\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Load power essential",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Watts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_topic",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/load_power_essential\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Load power non-essential",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Watts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_topic",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/load_power_non-essential\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Generator Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Watts" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_topic",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/generator_power\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  { "title": "Detail Graph General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Watts " } },
   "targets": [
    {
     "alias": "Load power",
     "query": "SELECT MEAN(\"value\") AS \"Load Power\"\nFROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/total\\/load_power\\/state/\nGROUP BY time($__interval) fill(null)\n"
    },
    {
     "alias": "Grid power",
     "query": "\nSELECT MEAN(\"value\") AS \"Grid Power\"\nFROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/total\\/grid_power\\/state/\nGROUP BY time($__interval) fill(null)\n"
    },
    {
     "alias": "Pv power",
     "query": "\nSELECT MEAN(\"value\") AS \"Pv power\"\nFROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/total\\/pv_power\\/state/\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  { "title": "MPPT 1 & 2 / PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MPPT 1 voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") AS \"PV Voltage\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_voltage_1\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "MPPT 1 current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Amperes" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"PV Current\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_current_1\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "MPPT 2 voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"PV Voltage\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_voltage_2\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "MPPT 2 current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Amperes" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"PV Current\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_current_2\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"PV Power\" FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_power\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "MPPT 1 power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"PV Power\" FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_power\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "PV power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") AS \"PV Power\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/pv_power\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Auxiliary PV power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Watts" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Netzbezug",
     "query": "SELECT MEAN(\"value\") AS \"Load Power\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /^.+\\/inverter_\\d\\/auxiliary_pv_power\\/state$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Load inverters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Load power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Inverter $tag_topic",
     "query": "\nSELECT last(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/load_power\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  { "title": "Grid and AC Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }, "repeat": "topicsEvuCurrent" },
  {
   "title": "Grid voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/grid_voltage\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/grid_frequency\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC output voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/ac_output_voltage\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT MEAN(\"value\") AS \"Total\" FROM \"state\" WHERE $timeFilter AND \"topic\" = 'solar_assistant_DEYE/total/ac_output_voltage/state' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batteries and Inverter Templerature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "Battery Temperature Info",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery temperature",
     "query": "SELECT last(\"value\") AS \"Battery Temperature\" FROM \"state\" WHERE \"topic\" =~ /.+\\/battery_\\d+\\/temperature\\/state/ ORDER BY time DESC LIMIT 1"
    },
    {
     "alias": "Battery Temperature Env",
     "query": "SELECT last(\"value\") AS \"Battery Temperature Env\" FROM \"state\" WHERE \"topic\" =~ /.+\\/battery_\\d+\\/temperature_env\\/state/ ORDER BY time DESC LIMIT 1"
    },
    {
     "alias": "Inverter Temperature $tag_topic",
     "query": "\nSELECT last(\"value\") \nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/inverter_\\d+\\/temperature\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Battery current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Amperes" } },
   "targets": [
    {
     "alias": "Inverter $tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"state\" WHERE $timeFilter AND \"topic\" =~ /.+\\/inverter_\\d+\\/battery_current\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") AS \"Total\" \nFROM \"state\" \nWHERE $timeFilter AND \"topic\" =~ /^.+\\/total\\/battery_current\\/state/ \nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Battery Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") AS \"Load Power\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/battery_\\d+\\/temperature\\/state/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT last(\"value\") \nFROM \"state\"\nWHERE \"topic\" =~ /.+\\/inverter_\\d+\\/temperature\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "Volts" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MEAN(\"value\") AS \"Battery Voltage\"\nFROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/inverter_\\d+\\/battery_voltage\\/state/ GROUP BY time($__interval), \"topic\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery state of charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "$tag_topic",
     "query": "SELECT MEAN(\"value\") AS \"Battery state of charge\" FROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/total\\/battery_state_of_charge\\/state/ GROUP BY time($__interval), \"topic\" fill(null)"
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Battery Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") AS \"Battery Power\"\nFROM \"state\"\nWHERE $timeFilter\nAND \"topic\" =~ /.+\\/total\\/battery_power\\/state/\nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}