#!/usr/bin/with-contenv bash
# ==============================================================================
# Start the Carbonoz service
# s6-overlay docs: https://github.com/just-containers/s6-overlay
# ==============================================================================

echo "[INFO] Starting Carbonoz SolarAutopilot..."

exec /usr/bin/carbonoz.sh